### ISSUE TITLE
Add LICENSE file?

### ISSUE THREAD

**Issue by ASnugglyBear** [toasterovenly/bgc#1]
This script looks great. I love the output and focus on paper. 

Can you put a LICENSE file in the directory so we know what we can use this for? I was going to stick a copy in the /r/boardgames organization if it was a OSS license that allowed that. 

https://choosealicense.com explains how to pick one. 

[Apache](https://choosealicense.com/licenses/apache-2.0/) is probably the one that most clearly welcomes people to use this however they wish. If you want to use that one, copy the text to a file with no extension. 

GPL3 + requiring contributors assign copyright to you is the one that most enables you to monetize this later if so inclined.

**Comment by toasterovenly** [comment]
Yeah. I will do that with the next release hopefully this weekend. Thanks
for the positive feedback.

**Comment by toasterovenly** [comment]
I added a license file (finally). Do you think I need to make another release for just adding a license?

**Comment by toasterovenly** [comment]
I added a license file (finally). Do you think I need to make another release for just adding a license?
